# docker run -d --name elasticsearch --net somenetwork -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:6.4.2
# docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.11.1
# docker-compose -f [filename] up -d
# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
---
version: '3.1'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    environment: 
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
       - 9200:9200
       - 9300:9300
    networks:
       - esnet
    volumes:
       - /data/elasticsearch/esdatas:/usr/share/elasticsearch/data

networks:
  esnet:
