# docker run -d --name elasticsearch --net somenetwork -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:6.4.2
# docker run --rm -it -v ~/pipeline/:/usr/share/logstash/pipeline/ docker.elastic.co/logstash/logstash:6.6.1
# docker run --rm -it -v ~/settings/:/usr/share/logstash/config/ docker.elastic.co/logstash/logstash:6.6.1
# docker run --rm -it -v ~/settings/logstash.yml:/usr/share/logstash/config/logstash.yml docker.elastic.co/logstash/logstash:6.6.1
# docker-compose -f [filename] up -d
# https://www.elastic.co/guide/en/logstash/current/docker.html
# https://www.elastic.co/guide/en/logstash/current/docker-config.html
---
version: '3.1'

services:
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.11.1
    environment: 
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "LOG_LEVEL=debug"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
       - 5044:5044
       - 9600:9600
    networks:
       - esnet
    volumes:
       - /data/logstash/config:/usr/share/logstash/config
       - /data/logstash/pipeline:/usr/share/logstash/pipeline

networks:
  esnet:
